name: easy_container
description: An easy to use container for flutter with built in gesture detectors and a lot of customization.
version: 0.0.7
homepage: https://github.com/rithik-dev/easy_container

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: