name: easy_container
description: An easy to use container for flutter with built in gesture detectors and a lot of customization.
version: 1.0.4+1
homepage: https://github.com/rithik-dev/easy_container
issue_tracker: https://github.com/rithik-dev/easy_container/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1