name: easy_container
description: An easy to use container for flutter with built in gesture detectors and a lot of customization.
version: 1.0.8
homepage: https://github.com/rithik-dev/easy_container
repository: https://github.com/rithik-dev/easy_container
issue_tracker: https://github.com/rithik-dev/easy_container/issues
documentation: https://github.com/rithik-dev/easy_container/blob/master/README.md

topics: 
  - flutter
  - widget
  - gesture
  - container
  - card

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
